#!/bin/bash
echo "--------------------------------------\n"
echo "You can run this "
mkdir -p /tmp/localdata

/cbfs/cbfs -nodeID=$mynodeid \
       -bucket=cbfs \
       -couchbase=http://$cbserver:8091/
       -root=/tmp/localdata \
       -viewProxy"
       
/cbfs/cbfsclient http://localhost:8484/ upload \
    /cbfs/monitor monitor
